// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI8iBGAIe4MW1R3_fz3zQ2hFbSdRo_v1Y',
    appId: '1:484518266518:web:1d6dfe2347e5c796e5e4b7',
    messagingSenderId: '484518266518',
    projectId: 'groz-52df0',
    authDomain: 'groz-52df0.firebaseapp.com',
    storageBucket: 'groz-52df0.firebasestorage.app',
    measurementId: 'G-G3M7R7KEES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6vI5s17D7hfjVAT2HuesZeRnCJDDvkwc',
    appId: '1:484518266518:android:b75fd643695337a7e5e4b7',
    messagingSenderId: '484518266518',
    projectId: 'groz-52df0',
    storageBucket: 'groz-52df0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI8iBGAIe4MW1R3_fz3zQ2hFbSdRo_v1Y',
    appId: '1:484518266518:web:08d08eed3136925be5e4b7',
    messagingSenderId: '484518266518',
    projectId: 'groz-52df0',
    authDomain: 'groz-52df0.firebaseapp.com',
    storageBucket: 'groz-52df0.firebasestorage.app',
    measurementId: 'G-SPCZHLRQQZ',
  );

}